apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dogs
  labels:
    app.kubernetes.io/name: dogs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dogs
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dogs
    spec:
      containers:
      - name: dogs
        image: 331023838533.dkr.ecr.us-east-1.amazonaws.com/dogs-ecr:latest
        ports:
        - containerPort: 80
        
        
